name: Execute Script

on:
  push:
    branches:
      - main

jobs:
  execute-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2
      - name: Installer dependances
        run: |
          pip install -r requirements.txt
      - name: Convertir les notebooks 
        run: |
          jupyter nbconvert --to script notebooks/03_Developement_Modele.ipynb script notebooks/02_Pre_traitement.ipynb
          mv notebooks/*.py credit_risk
      - name: Generer le modele 
        run: |
          cd credit_risk
          python 02_Pre_traitement.py
          python 03_Developement_Modele.py       
      - name: Commitar e pushar arquivos
        run: |
          git config --global user.email "cleriston@gmail.com"
          git config --global user.name "Cleriston Martinelo"
          git add .
          git commit -m "MAJ du modele"
          git push origin HEAD:main

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

